language: node_js

node_js:
  - "11.3.0"

git:
  submodules: false

services:
  - postgresql

addons:
  postgresql: "9.6"

before_install:
  - psql -c "create role admin with superuser login password 'admin';" -U postgres
  - psql -c "create database todos with owner admin;" -U postgres
  - psql -c "create database automatedqa with owner admin;" -U postgres

install:
  - (cd manager && npm install)
  - (cd test-service && npm install)
  - (cd manager && npm run build)
  - (cd test-service && npm run build)
  - git clone https://github.com/kiasaki/automated-qa-worker
  - (cd automated-qa-worker && npm install)

before_script:
  - node manager/scripts/setupDatabase.js
  - node test-service/scripts/setupDatabase.js

script:
  - (cd test-service && node dist/index.js&)
  - (cd automated-qa-worker && node example/index.js&)
  - (cd manager && npm run test)
